[API] Endpoint do zwracania listy wszystkich zamówień dla konkretnego użytkownika
husi-cetuspro/cetusfood-back-end pull request #13
Opened 2022-07-28 08:33 UTC by WiktorDev

2022-07-28 09:43 UTC, husi-cetuspro requested changes

2022-07-28 09:43 UTC, husi-cetuspro commented on src/api/profile/shared/shared.profile.service.ts
> +                    }
if(product)
                        totalCoast += product.price
                    
Możesz napisać w ten sposób bez `{}` klamerek :D

2022-07-28 09:43 UTC, husi-cetuspro commented on src/shedule/shedule.service.ts
> +                    if(order.status == Status.PENDING){
Zamiast tych dwóch ifów możesz zrobić coś takiego:

`if(order.restaurantId !== resteurant.id && order.status !== Status.PENDING) break;`

I wtedy cała pętla będzie wyglądać tak:
```
            for (const order of orders) {
                if(order.restaurantId !== resteurant.id && order.status !== Status.PENDING) break;

                try{
                    let orderItem = await this.prismaService.orderItem.findFirst({ where: { orderId: order.id }});
                    let product = await this.prismaService.product.findFirst({ where: { id: orderItem.productId }})

                    items.push(product)

                    await this.prismaService.order.update({
                        data: { status: Status.DELIVERED },
                        where: { id: order.id }
                    })
                }catch (error){
                    Logger.error(error);
                }
            }
```

Nie testowałem czy na pewno działa ale powinno :)

2022-07-28 09:43 UTC, husi-cetuspro commented on src/shedule/shedule.service.ts
> +            let orders = await this.prismaService.order.findMany()
Tutaj pobierasz chyba wszystkie zamówienia. Może lepiej było pobierać tylko te z ostatniego dnia, albo te o statusie `PENDING`? Też wtedy nie musiałbyś robić tego if'a `order.status !== Status.PENDING`

2022-07-28 09:43 UTC, husi-cetuspro commented on src/shedule/shedule.service.ts
> +            let orders = await this.prismaService.order.findMany()
A i też tutaj można byłoby chyba pobrać tylko te zamówienia z konkretnej restauracji. Trzeba byłoby dodać jakiegoś WHERE że id restauracji musi być równe `resteurant.id`

Wtedy nie będziesz potrzebował też tego drugiego if'a i będziesz miał mniej danych do pobrania

2022-07-28 09:55 UTC, husi-cetuspro commented on src/api/profile/shared/shared.profile.service.ts
> +                if(order && order.status == Status.COMPLETED){
Tutaj też zamiast robić tego if'a możesz od razu pobrać z bazy tylko zamówienia o statusie "COMPLETED"

2022-07-28 09:56 UTC, husi-cetuspro commented on src/api/profile/shared/shared.profile.service.ts
> +            let totalCoast = 0;
Tutaj jest literówka, powinno być `totalCosts`

2022-07-28 09:57 UTC, husi-cetuspro commented on src/main.ts
> +	});
Bardzo fajnie :D

2022-07-28 10:03 UTC, husi-cetuspro commented on src/shedule/shedule.service.ts
>          }
Przy archiwizacji zamówień dobrze byłoby nie pobierać wszystkich zamówień, a jedynie te z ostatniego miesiąca lub też zamiast pobierać może lepiej będzie od razu nadpisać status? Zrobić coś takiego `UPDATE orders SET status="ARCHIVE" WHERE status!="CANCELLED";`

Nie wiem jak to zrobić w prisma ale może ty ogarniesz o co chodzi i jak to zrobić

Przy większej ilości zamówień pętla będzie zbyt mało wydajna

2022-07-28 10:19 UTC, WiktorDev commented on src/api/profile/shared/shared.profile.service.ts
> +                if(order && order.status == Status.COMPLETED){
Tutaj nie moge tak zrobic poniewaz ten if jest do liczenia ile trzeba zaplacic za zamowienia o statusie COMPLETED. A potem sa zwracane wszystkie zamowienia, lub o takim statusie jaki zostanie podany w endpoincie

2022-07-28 10:21 UTC, Packman700 requested changes

2022-07-28 10:21 UTC, Packman700 commented on src/api/profile/admin/admin.profile.controller.ts
> +    public async getUserProfile(@Param("id") id: string, @Query("status") status: string){
Zapewnie status jest jakimś enumem możesz więc to otypować 
`
@Query("status") status: PRISMA_STATUS
`

+ status nie mówi o jaki chodzi status zastanów się czy nie lepszą nazwą byłoby np. acticeStatus

2022-07-28 10:21 UTC, Packman700 commented on src/api/profile/admin/admin.profile.controller.ts
> +    public async getUserProfile(@Param("id") id: string, @Query("status") status: string){
Stwórz własny dekorator który będzie konwerwoać stringa na int 
Ułatwi ci to życie ;D

2022-07-28 10:21 UTC, Packman700 commented on src/api/profile/shared/shared.profile.service.ts
> +    public async getUserProfile(id: string, status: string){
Funkcja nie ma typu który jest zwracany 
Zastanów się nad stworzeniem entity

2022-07-28 10:21 UTC, Packman700 commented on src/api/profile/admin/admin.profile.controller.ts
> +    public async getUserProfile(@Param("id") id: string, @Query("status") status: string){
Funkcja nie ma typu który jest zwracany 
Zastanów się nad stworzeniem entity

2022-07-28 10:21 UTC, Packman700 commented on src/api/profile/shared/shared.profile.service.ts
> +    public async getUserProfile(id: string, status: string){
Ten parametr status powinien być typu Status a nie string

2022-07-28 10:21 UTC, Packman700 commented on src/exceptions/invalidValue.exception.ts
> +export class InvalidValueException extends HttpException{
O super że tworzysz własne błędy 
Jedyne co mogę zasugerować to stworzeni więcej błędów które określą dokładnie jaka wartość jest nieprawidłowa 
Uwierz ułatwia to potem życie na fronice + debugging

2022-07-28 10:21 UTC, Packman700 commented on src/main.ts
> +	});
O kurcze nice nawet u nas nie działają credentials xD

2022-07-28 10:21 UTC, Packman700 commented on src/shedule/shedule.service.ts
> +                if(order.restaurantId === resteurant.id){
Zamiast sprawdzać później czy `order.restaurantId === resteurant.id` doda where do `await this.prismaService.order.findMany()`
np 
``await this.prismaService.order.findMany({where:{restaurantId: restaurantId}})`
Jeśli nie masz takiej relacji to stwóż ją ;D

2022-07-28 10:24 UTC, husi-cetuspro commented on src/api/profile/admin/admin.profile.controller.ts
> +    public async getUserProfile(@Param("id") id: string, @Query("status") status: string){
`actice`?

2022-07-28 10:28 UTC, WiktorDev commented on src/shedule/shedule.service.ts
> +                    if(order.status == Status.PENDING){
Tutaj nie moze byc break bo jak jest kilka elementow o statusie np:
0: PENDING
1: CANCELLED
2: PENDING

to petla zatrzyma sie na indeksie 1 i juz nie pojdzie dalej

2022-07-28 10:54 UTC, Packman700 commented on src/api/profile/admin/admin.profile.controller.ts
> +    public async getUserProfile(@Param("id") id: string, @Query("status") status: string){
Yep :')

2022-07-28 14:28 UTC, husi-cetuspro commented on src/api/profile/admin/admin.profile.controller.ts
> +    public async getUserProfile(@Param("id") id: string, @Query("status") status: string){
A co to jest actice? ;D

2022-07-28 14:31 UTC, husi-cetuspro commented on src/api/profile/shared/shared.profile.service.ts
> +                if(order && order.status == Status.COMPLETED){
To myślę, że warto rozdzielić to na dwa endpointy: jeden do zwracania ile trzeba zapłacić, a drugi do zwracania zamówień o konkretnym statusie. 

Na froncie pewnie będą osobne zakładki do listy zamówień i do rozliczeń, więc tutaj też warto byłoby to moim zdaniem rozdzielić :)

2022-07-28 14:39 UTC, husi-cetuspro commented on src/shedule/shedule.service.ts
> +                    let orderItem = await this.prismaService.orderItem.findFirst({ where: { orderId: order.id }});
Tutaj używasz `findFirst` czy to jest okej? Co gdy jedno zamówienie będzie miało kilka itemów?

2022-07-28 14:40 UTC, husi-cetuspro commented on src/shedule/shedule.service.ts
> +                    let product = await this.prismaService.product.findFirst({ where: { id: orderItem.productId }})
Nie do końca rozumiem te dwie linie 31 oraz 32. Tutaj używasz `findFirst` czy to jest okej? Co gdy jedno zamówienie będzie miało kilka itemów?

2022-07-29 15:16 UTC, husi-cetuspro commented on src/shedule/shedule.service.ts
> +                    if(order.status == Status.PENDING){
A to czekaj, nie wiem jak to zrobić, ale da się zrobić tak jakby skip? Aby nie przerywało całej pętli tylko pominęło dany index

2022-07-29 15:24 UTC, husi-cetuspro commented on src/shedule/shedule.service.ts
> +                    }
Da się zrobić tak, aby zapisać pierwsze do tablicy wszystkie id produktów i później przekazać te id do zapytania ale tak aby było w jednym zapytaniu?

Może da się przekazać te id po przecinku albo zrobić jakiegoś OR'a

2022-07-29 15:25 UTC, husi-cetuspro commented on src/api/orders/user/user.orders.service.ts
> +import {Status} from "../../../enums/status.enum";
Warto napisać dokładniej jaki to jest status. Później będziemy mieć status zamówienia, status rozliczenia itp

Można to dać do osobnych folderów albo zmienić nazwę :)

Ale ogólnie na plus że to przeniosłeś do osobnego folderu a nie że zostało w folderze `src` :)

2022-07-29 15:26 UTC, husi-cetuspro commented on src/api/orders/user/user.orders.service.ts
> +import {Status} from "../../../enums/status.enum";
Jeszcze takie pytanie, da się używać tutaj `@/enums/status.enum`. Tak aby nie cofać się przez `../` tylko aby od razu pisać ścieżkę od poziomu `src`

2022-07-29 16:25 UTC, WiktorDev commented on src/shedule/shedule.service.ts
> +                    if(order.status == Status.PENDING){
continue powinno tak zadzialac

2022-07-29 16:31 UTC, WiktorDev commented on src/api/orders/user/user.orders.service.ts
> +import {Status} from "../../../enums/status.enum";
te importy mi sie automatycznie generuja, ale mozna to zmienic

2022-08-03 06:47 UTC, merged